### ISSUE TITLE
GAN NMT

### ISSUE THREAD

**Issue by Bachstelze** [RedditSota/state-of-the-art-result-for-machine-learning-problems#11]
paper: Improving Neural Machine Translation with Conditional Sequence Generative Adversarial Nets https://arxiv.org/abs/1703.04887
year: 2107
average BLEU score in chinese - english NIST03 to NIST05 task up to 42.6 points
implementation: https://github.com/ngohoanhkhoa/GAN-NMT

**Comment by RedditSota** [comment]
Thank you for your contriubtion
