### ISSUE TITLE
Speech section

### ISSUE THREAD

**Issue by dmitriy-serdyuk** [RedditSota/state-of-the-art-result-for-machine-learning-problems#25]
There is an existing repo for speech SOTAs: https://github.com/syhw/wer_are_we. Perhaps, you want to reference them and/or join forces with them.

Concerning the Switchboard number, you need to mention that it used 2000h set for training and the Switchboard Hub5'00 for testing (not Call Home subset).

**Comment by RedditSota** [comment]
Thanks. Will do it.
