### ISSUE TITLE
A website that might be useful

### ISSUE THREAD

**Issue by githwd2016** [RedditSota/state-of-the-art-result-for-machine-learning-problems#31]
I find a website on which there are some state of the art objects classification results. I hope it will be useful. The link is:
http://rodrigob.github.io/are_we_there_yet/build/classification_datasets_results.html

**Comment by lucaventurini** [comment]
Also: https://paperswithcode.com/sota

This project could as well become a wikipedia page, like https://en.wikipedia.org/wiki/List_of_datasets_for_machine_learning_research

**Comment by taoyudong** [comment]
Thanks for the recommendation. There're a lot of excellent jobs done in the community to collect STOA from papers and I am also thinking what this project can contribute without duplicating the efforts from the others. Thanks for the suggestion. I will think about the wiki page.
