### ISSUE TITLE
Updated Speech recognition SOTA result.

### ISSUE THREAD

**Issue by CMSFlash** [RedditSota/state-of-the-art-result-for-machine-learning-problems#38]
According to [Speech SOTA](https://github.com/syhw/wer_are_we), the new state of the art on Switchboard Hub5'00 is [The CAPIO 2017 Conversational Speech Recognition System](https://arxiv.org/abs/1801.00059), at WER of 5.0%, published in Dec., 2017.

**Comment by taoyudong** [comment]
I have updated as you suggest. Thanks for the help.
