### ISSUE TITLE
Your email address `redditsota@gmail.com` was not found

### ISSUE THREAD

**Issue by zixia** [RedditSota/state-of-the-art-result-for-machine-learning-problems#39]
I had just sent an email to `redditsota@gmail.com` however it seems not work

```
Address not found
--
Your message wasn't delivered to redditsota@gmail.com because the address couldn't be found, or is unable to receive mail.

The response was:The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces. Learn more at https://support.google.com/mail/?p=NoSuchUser r20-v6sor96536itb.73 - gsmtp
```

So I just post my email at here ;)

> Hi there,
> 
> I'm a machine learning newbie with 20 years of programming experience. I love ML and this year I'll go for my Ph.D. study for ChatBot(NLU, ChatUI) in Beijing.
> 
> I'm willing to help as a collaborator because I love your idea of making one stop for all types of machine learning problems state of the art result, it helps me much.
> 
> Please feel free to let me know what I could do for you at any time. 
> 
> My GitHub: https://github.com/zixia
> My LinkedIn: https://linkedin.com/in/zixia
> My WeChat: 918999
> 
> Have a nice day!
>
> Huan LI
> zixia@zixia.net

**Comment by Namrata96** [comment]
yes, I've received a similar email. Please let us know an alternative email ID.

**Comment by taoyudong** [comment]
I think the original author becomes inactive now. If you are still interested in this repo, please feel free to pull request. I will try to accept the request as soon as I am available.

**Comment by taoyudong** [comment]
If you have a strong interest to build a better SOTA tracking repo, please contact me at ydt115870 at gmail dot com. I have plans to build a better system to help the community keep track of SOTA and the historical trend of the technique development.
