### ISSUE TITLE
STOA of Unsupervised Learning for Machine Translation

### ISSUE THREAD

**Issue by dqqcasia** [RedditSota/state-of-the-art-result-for-machine-learning-problems#49]
Research Paper:
Unsupervised Neural Machine Translation with Weight Sharing
Datasets:

1.WMT14+16(en-fr fr-en de-en en-de)
2.LDC(zh-en)
Metric:
1.BLEU:(16.97 15.58 14.62 10.86) 
2.BLEU:(14.52) 
Source Code:
https://github.com/ZhenYangIACAS/unsupervised-NMT
Year:
2018

**Comment by taoyudong** [comment]
The issue is delivered in the most recent update: 5365bfa8e7f530c8d1657bff1bced064df71abdc

**Comment by taoyudong** [comment]
Thanks for your contribution. Please let me know if you are aware any advances in any of the area.
