### ISSUE TITLE
Source code URLs for 2 paper in the Text Classification part

### ISSUE THREAD

**Issue by XiaoningCui** [RedditSota/state-of-the-art-result-for-machine-learning-problems#58]
1. Source code URL for [Learning Structured Text Representations](https://github.com/nlpyang/structured)
2. Source code URL for [Attentive Convolution](https://github.com/yinwenpeng/Attentive_Convolution)

**Comment by taoyudong** [comment]
I have updated the information. Thanks!
Looking forward to your future contribution.
