### ISSUE TITLE
Past SoTA

### ISSUE THREAD

**Issue by taoyudong** [RedditSota/state-of-the-art-result-for-machine-learning-problems#6]
It will be good if a track of SoTA can be provided, listing the path of how the tech is developed.
I may be able to help in some of the areas

**Comment by RedditSota** [comment]
Great. It takes time but a good idea.

**Comment by taoyudong** [comment]
Yeah.

 

Will work on it when I have time~

 

Whenever get chance, I will contribute more~

**Comment by RedditSota** [comment]
Awesome. Will add you
