### ISSUE TITLE
add ImageNet results to Giant AmoebaNet

### ISSUE THREAD

**Issue by scott-vsi** [RedditSota/state-of-the-art-result-for-machine-learning-problems#60]
The [Giant AmoebaNet](https://arxiv.org/pdf/1811.06965.pdf) claims SoTA results on ImageNet of 84.3% top-1 accuracy, beating the 2017 ImageNet winner, [Squeeze-and-Excitation Networks](https://arxiv.org/pdf/1709.01507.pdf). Should these be listed along with the CIFAR-10 and CIFAR-100 results?

(also, Gaint is misspelled. It should be Giant)

**Comment by taoyudong** [comment]
Delivered in the commit 56914c2. Thanks for your suggestion.
Looking forward to your future contribution.
