### ISSUE TITLE
Natural Language Inference SoTA result

### ISSUE THREAD

**Issue by YichenGong** [RedditSota/state-of-the-art-result-for-machine-learning-problems#7]
SNLI Leaderboard
https://nlp.stanford.edu/projects/snli/

MultiNLI Leaderboard
https://www.kaggle.com/c/multinli-matched-open-evaluation/leaderboard

SoTA: Densely Interactive Inference Network
Paper: https://arxiv.org/pdf/1709.04348.pdf
Code: https://github.com/YichenGong/Densely-Interactive-Inference-Network

**Comment by RedditSota** [comment]
Thank you

**Comment by RedditSota** [comment]
Updated. Thank you for your contribution.
